#定义流水线全局阶段
stages:
  - deploy

variables:
  APP_NAME: local_test
  PROJECT_PORT: 9501
  DOCKER_IMAGE_NAME: docker_hyperf_${APP_NAME}
  DOCKER_CONTAINER_PORT: 9501

#发布到测试环境
deploy to test:
  stage: deploy
  # tags ：指定流水线使用哪个runner去运行，只能定义到一个具体的项目，tags的取值范围是该项目可见的runner
  tags:
    - test
  # environment ：部署的环境名称
  environment:
    name: test
  # only ：限定某些分支或者某些tag
  only:
    - test
  # variables : 定义全局变量
  variables:
    # 声明一个变量叫 DOT_ENV , ${xx} 引入定义的变量，一般情况env文件的内容可以写在【setting -> ci/cd -> Variables】中，通过${}来获取
    # 最后由下面的script的脚本来生成.env : echo "${DOT_ENV}" > .env
    DOT_ENV: ${DOT_ENV_TEST}
  # 由runner执行的shell脚本（必填项）
  script:
    - rm -rf phpunit.xml
    - rm -rf .git
    - rm -rf README.md
    - echo "${DOT_ENV}" > dotenv
    - echo "${DOT_ENV}" > .env
    - docker build -t ${DOCKER_IMAGE_NAME} .
    - docker rm -f ${APP_NAME}
    - docker run -d --name ${APP_NAME} --restart=always -p ${PROJECT_PORT}:${DOCKER_CONTAINER_PORT} ${DOCKER_IMAGE_NAME}
  after_script:
    - docker rmi $(docker images -f "dangling=true" -q)